language: python
sudo: true
matrix:
  include:
    - python: "3.4"
      env: TOX_ENV=pep8
    - python: "3.4"
      env: TOX_ENV=py34
install:
  - pip install tox
  - if [[ $TOX_ENV == py34 ]]; then
      pip install coveralls;
      wget --quiet -c https://www.sqlite.org/2016/sqlite-autoconf-3140100.tar.gz;
      tar zxf sqlite-autoconf-3140100.tar.gz; cd sqlite-autoconf-3140100; ./configure --prefix=$HOME/local; make; make install; cd ..; rm -fr sqlite-autoconf-3140100;
    fi
script:
  - sqlite3 --version
  - tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == py34 ]]; then
      coveralls;
    fi
