language: python
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
matrix:
  include:
    - python: "3.4"
      env: TOX_ENV=pep8
    - python: "3.4"
      env: TOX_ENV=py34
install:
  - pip install tox
  - if [[ $TOX_ENV == py34 ]]; then
      pip install coveralls;
    fi
script:
  - cat ~/apt-get-update.log
  - sqlite3 --version
  - tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == py34 ]]; then
      coveralls;
    fi
