language: python
sudo: true
matrix:
  include:
    - python: "3.4"
      env: TOX_ENV=pep8
    - python: "3.4"
      env: TOX_ENV=py34
before_install:
  - if [[ $TOX_ENV == py34 ]]; then
      wget http://sqlite.org/2017/sqlite-autoconf-3190200.tar.gz;
      tar -xzvf sqlite-autoconf-3190200.tar.gz;
      cd sqlite-autoconf-3190200;
      CFLAGS="-Os" ./configure -prefix=/usr && make && sudo make install;
    fi
install:
  - pip install tox
  - if [[ $TOX_ENV == py34 ]]; then
      pip install coveralls;
    fi
script:
  - cat ~/apt-get-update.log
  - sqlite3 --version
  - tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == py34 ]]; then
      coveralls;
    fi
