language: python
sudo: true
matrix:
  include:
    - python: "3.4"
      env: TOX_ENV=pep8
    - python: "3.4"
      env: TOX_ENV=py34
before_install:
  - if [[ $TOX_ENV == py34 ]]; then
      wget --quiet -c http://sqlite.org/2017/sqlite-autoconf-3190200.tar.gz;
      tar -zxvf sqlite-autoconf-3190200.tar.gz;
      cd sqlite-autoconf-3190200;
      ./configure --prefix=/usr;
      make;
      make install;
      cd ..;
      rm -fr sqlite-autoconf-3190200;
    fi
install:
  - pip install tox
  - if [[ $TOX_ENV == py34 ]]; then
      pip install coveralls;
    fi
script:
  - sqlite3 --version
  - tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == py34 ]]; then
      coveralls;
    fi
